name: 'web-lib'
services:
  php-dev:
    build:
      additional_contexts:
        docker-files: .docker/
      args:
        - PHP_VERSION
      context: .
      dockerfile: .docker/Dockerfile
      target: php_dev
    container_name: ${COMPOSE_PROJECT_NAME}-php-dev
    environment:
      - XDEBUG_MODE
    image: 'maxie-systems/${COMPOSE_PROJECT_NAME}-php:dev'
    restart: unless-stopped
    tty: true
    volumes:
      - .:/usr/src/app/
