name: 'web-lib-dev'
services:
  php:
    build:
      args:
        - PHP_VERSION
      context: .
      dockerfile: .docker/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-php
    environment:
      - XDEBUG_MODE
    image: 'maxie-systems/web-lib-dev:latest'
    restart: unless-stopped
    tty: true
    volumes:
      - .:/usr/src/app/
