name: 'web-lib-test'

x-php-service: &php-service
  build: &php-build
    additional_contexts:
      source: ../.
    args:
      - PHP_VERSION
    target: php_test

services:
  php-83:
    command: ["run-tests", "phpunit"]
    environment:
      XDEBUG_MODE: coverage
    extends:
      service: php-lint-83
  php-82:
    <<: *php-service
    build:
      <<: *php-build
      args:
        PHP_VERSION: 8.2
    depends_on:
      php-83:
        condition: service_completed_successfully
  php-lint-83:
    <<: *php-service
    build:
      <<: *php-build
      args:
        PHP_VERSION: 8.3
    command: ["run-tests", "phpcs", "phpstan"]
