name: 'web-lib-test'

x-php-service: &php-service
  build: &php-build
    additional_contexts:
      docker-files: ../.docker/
    args:
      - PHP_VERSION
    context: ../.
    dockerfile: .docker/Dockerfile
    target: php_test
  command: ["run-tests", "no-coverage"]

services:
  php-83:
    <<: *php-service
    build:
      <<: *php-build
      args:
        PHP_VERSION: 8.3
    command: ["run-tests", "coverage"]
    environment:
      XDEBUG_MODE: coverage
  php-82:
    <<: *php-service
    build:
      <<: *php-build
      args:
        PHP_VERSION: 8.2
    depends_on:
      php-83:
        condition: service_completed_successfully
# For the future usage:
#  php-84:
#    <<: *php-service
#    build:
#      <<: *php-build
#      args:
#        PHP_VERSION: 8.4
#    depends_on:
#      php-83:
#        condition: service_completed_successfully
