name: Run tests (PHPUnit & phpcs)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    types: [ opened, reopened, edited, ready_for_review ]
    branches: [ "main", "dev" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  PHP_VERSION: 8.2

jobs:
  run-tests:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          args: --classmap-authoritative --no-progress

      - name: Validate composer.json and composer.lock
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          command: validate
          args: --strict --with-dependencies

      - name: Create temporary folder
        run: mkdir var/

      - name: Run test suite
        uses: php-actions/composer@v6
        env:
          XDEBUG_MODE: coverage
        with:
          php_version: ${{ env.PHP_VERSION }}
          php_extensions: xdebug
          command: exec
          only_args: phpunit

      - name: Code coverage report
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          command: code-coverage-report
          only_args: --ignore-threshold

      - name: Check code against the PSR-12 coding standard
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          command: run-script
          only_args: test-psr12-all
