name: Run tests (PHPUnit & phpcs)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    types: [ opened, reopened, edited, ready_for_review ]
    branches: [ "main", "dev" ]

permissions:
  contents: read

env:
  PHP_VERSION: 8.2

jobs:
  build-test:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          args: --classmap-authoritative

      - name: Validate composer.json and composer.lock
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          command: validate
          args: --strict --with-dependencies

      - name: Run test suite
        uses: php-actions/composer@v6
        env:
          XDEBUG_MODE: coverage
        with:
          php_version: ${{ env.PHP_VERSION }}
          php_extensions: xdebug
          command: run-script
          only_args: test-all
