name: Run tests (PHPUnit & phpcs)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

env:
  PHP_VERSION: 8.2

jobs:
  build-test:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        id: composer_install
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}

      - name: Validate composer.json and composer.lock
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          command: validate
          args: --strict --with-dependencies

      - name: Run test suite
        uses: php-actions/composer@v6
        env:
          XDEBUG_MODE: coverage
        with:
          php_version: ${{ env.PHP_VERSION }}
          php_extensions: xdebug
          command: run-script
          only_args: test-all

#     - name: PHPUnit Tests
#       uses: php-actions/phpunit@v3
#       env:
#         XDEBUG_MODE: coverage
#       with:
#         bootstrap: vendor/autoload.php
#         configuration: phpunit.xml
#         php_extensions: xdebug
#         args: tests --coverage-clover ./coverage.xml

#     - name: Upload to Codecov
#       uses: codecov/codecov-action@v2
#       with:
#         token: ${{ secrets.CODE_COV_TOKEN }}
#         files: ./coverage.xml
#         verbose: true
