name: Run tests (PHPUnit & phpcs)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build-test:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.2
    

#    - name: Validate composer.json and composer.lock
#      run: composer validate --strict

#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v3
#      with:
#        path: vendor
#        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-php-

#    - name: Install dependencies
#      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        run: composer run-script test-all

# ---

#     - name: PHPUnit Tests
#       uses: php-actions/phpunit@v3
#       env:
#         XDEBUG_MODE: coverage
#       with:
#         bootstrap: vendor/autoload.php
#         configuration: phpunit.xml
#         php_extensions: xdebug
#         args: tests --coverage-clover ./coverage.xml

#     - name: Upload to Codecov
#       uses: codecov/codecov-action@v2
#       with:
#         token: ${{ secrets.CODE_COV_TOKEN }}
#         files: ./coverage.xml
#         verbose: true
